<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Moves extends \Entities\Moves implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setAccessToken($accessToken)
    {
        $this->__load();
        return parent::setAccessToken($accessToken);
    }

    public function getAccessToken()
    {
        $this->__load();
        return parent::getAccessToken();
    }

    public function setExpiresIn($expiresIn)
    {
        $this->__load();
        return parent::setExpiresIn($expiresIn);
    }

    public function getExpiresIn()
    {
        $this->__load();
        return parent::getExpiresIn();
    }

    public function setRefreshToken($refreshToken)
    {
        $this->__load();
        return parent::setRefreshToken($refreshToken);
    }

    public function getRefreshToken()
    {
        $this->__load();
        return parent::getRefreshToken();
    }

    public function setMovesUserId($movesUserId)
    {
        $this->__load();
        return parent::setMovesUserId($movesUserId);
    }

    public function getMovesUserId()
    {
        $this->__load();
        return parent::getMovesUserId();
    }

    public function setUserApps(\Entities\UserApps $userApps = NULL)
    {
        $this->__load();
        return parent::setUserApps($userApps);
    }

    public function getUserApps()
    {
        $this->__load();
        return parent::getUserApps();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'accessToken', 'expiresIn', 'refreshToken', 'movesUserId', 'userApps');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}